---
#
# Ansible managed
#
repository:
  description: Check diskspace (or inodes) available, fail if too low.
  homepage: https://robertdebock.nl/
  topics: diskspace, inodes, assert, check, system, ansible, molecule, playbook
